apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:15
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: pg-secret
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: pg-secret
            key: POSTGRES_DB
    volumeMounts:
      - name: pgdata
        mountPath: /var/lib/postgresql/data
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: pg-pvc
